Support Sphinx (#92)
Fix minor PAT descriptions in docs.
Group inputs in workflows for improved readability.
Add `build_libs` input to CD - Release to mirror CI - Tests.
Fix minor issues in CD - Release.

Support using Sphinx in CI - Tests.
Support Sphinx for CD - Release
Support Sphinx in CI/CD - New updates to default branch

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -3,28 +3,16 @@ name: CI - Tests
 on:
   workflow_call:
     inputs:
+      # General
+      install_extras:
+        description: "Any extras to install from the local repository through 'pip'. Must be encapsulated in square parentheses (`[]`) and be separated by commas (`,`) without any spaces. Example: `'[dev,pre-commit]'`."
+        required: false
+        type: string
+        default: ""
+
+      # pre-commit
       run_pre-commit:
         description: "Run the `pre-commit` test job."
-        required: false
-        type: boolean
-        default: true
-      run_pylint:
-        description: "Run the `pylint` test job."
-        required: false
-        type: boolean
-        default: true
-      run_safety:
-        description: "Run the `safety` test job."
-        required: false
-        type: boolean
-        default: true
-      run_build_package:
-        description: "Run the 'build package' test job."
-        required: false
-        type: boolean
-        default: true
-      run_build_docs:
-        description: "Run the 'build documentation' test job."
         required: false
         type: boolean
         default: true
@@ -33,36 +21,24 @@ on:
         required: false
         type: string
         default: "3.9"
-      python_version_pylint_safety:
-        description: "The Python version to use for the `pylint` and `safety` test jobs."
-        required: false
-        type: string
-        default: "3.9"
-      python_version_package:
-        description: "The Python version to use for the `build package` test job."
-        required: false
-        type: string
-        default: "3.9"
-      python_version_docs:
-        description: "The Python version to use for the `build documentation` test job."
-        required: false
-        type: string
-        default: "3.9"
-      install_extras:
-        description: "Any extras to install from the local repository through 'pip'. Must be encapsulated in square parentheses (`[]`) and be separated by commas (`,`) without any spaces. Example: `'[dev,pre-commit]'`."
-        required: false
-        type: string
-        default: ""
-      relative:
-        description: "Whether or not to use install the local Python package(s) as an editable, _only_ when running the `build_docs` job."
-        required: false
-        type: boolean
-        default: false
       skip_pre-commit_hooks:
         description: "A comma-separated list of pre-commit hook IDs to skip when running `pre-commit` after updating hooks."
         required: false
         type: string
         default: ""
+
+      # pylint & safety
+      python_version_pylint_safety:
+        description: "The Python version to use for the `pylint` and `safety` test jobs."
+        required: false
+        type: string
+        default: "3.9"
+
+      run_pylint:
+        description: "Run the `pylint` test job."
+        required: false
+        type: boolean
+        default: true
       pylint_options:
         description: "Single space-separated or multi-line string of pylint command line options. Note, this is only valid if 'pylint_runs' is not defined."
         required: false
@@ -78,11 +54,29 @@ on:
         required: false
         type: string
         default: ""
+
+      run_safety:
+        description: "Run the `safety` test job."
+        required: false
+        type: boolean
+        default: true
       safety_options:
         description: "Single space-separated or multi-line string of safety command line options."
         required: false
         type: string
         default: ""
+
+      # Build package / distribution
+      run_build_package:
+        description: "Run the 'build package' test job."
+        required: false
+        type: boolean
+        default: true
+      python_version_package:
+        description: "The Python version to use for the `build package` test job."
+        required: false
+        type: string
+        default: "3.9"
       build_libs:
         description: "A space-separated list of packages to install via PyPI (`pip install`)."
         required: false
@@ -93,6 +87,40 @@ on:
         required: false
         type: string
         default: "python -m build"
+
+      # Build documentation
+      run_build_docs:
+        description: "Run the 'build documentation' test job."
+        required: false
+        type: boolean
+        default: true
+      python_version_docs:
+        description: "The Python version to use for the `build documentation` test job."
+        required: false
+        type: string
+        default: "3.9"
+      relative:
+        description: "Whether or not to use the locally installed Python package(s), and install it as an editable, _only_ when running the `build_docs` job."
+        required: false
+        type: boolean
+        default: false
+      system_dependencies:
+        description: "A single (space-separated) or multi-line string of Ubuntu APT packages to install prior to building the documentation."
+        required: false
+        type: string
+        default: ""
+      warnings_as_errors:
+        description: "Build the documentation in 'strict' mode, treating warnings as errors. **Important**: If this is set to `false`, beware that the documentation may _not_ be rendered or built as one may have intended. Default: `true`."
+        required: false
+        type: boolean
+        default: true
+
+      # MkDocs
+      use_mkdocs:
+        description: "Whether or not to build the documentation using the MkDocs framework. Mutually exclusive with `use_sphinx`."
+        required: false
+        type: boolean
+        default: false
       update_python_api_ref:
         description: "Whether or not to update the Python API documentation reference. **Note**: If this is 'true', 'package_dirs' is _required_."
         required: false
@@ -143,16 +171,33 @@ on:
         required: false
         type: string
         default: ","
-      warnings_as_errors:
-        description: "Build the documentation in 'strict' mode, treating warnings as errors. **Important**: If this is set to `false`, beware that the documentation may _not_ be rendered or built as one may have intended. Default: `true`."
-        required: false
-        type: boolean
-        default: true
       debug:
         description: "Whether to do print extra debug statements."
         required: false
         type: boolean
         default: false
+
+      # Sphinx
+      use_sphinx:
+        description: "Whether or not to build the documentation using the Sphinx framework. Mutually exclusive with `use_mkdocs`."
+        required: false
+        type: boolean
+        default: false
+      sphinx-build_options:
+        description: "Single (space-separated) or multi-line string of command-line options to use when calling `sphinx-build`. Note, the `-W` option will be added if 'warnings_as_errors' is 'true' (default)."
+        required: false
+        type: string
+        default: ""
+      docs_folder:
+        description: "The path to the root documentation folder relative to the repository root. Defaults to 'docs'."
+        required: false
+        type: string
+        default: "docs"
+      build_target_folder:
+        description: "The path to the target folder for the documentation build relative to the repository root. Defaults to 'site'."
+        required: false
+        type: string
+        default: "site"
 
 jobs:
   pre-commit:
@@ -262,11 +307,30 @@ jobs:
       run: ${{ inputs.build_cmd }}
 
   docs:
-    name: Build MkDocs Documentation
+    name: Build Documentation
     if: inputs.run_build_docs
     runs-on: ubuntu-latest
 
     steps:
+    - name: Determine framework
+      run: |
+        if [[ \
+          ("${{ inputs.use_mkdocs }}" == "false" && "${{ inputs.use_sphinx }}" == "false") || \
+          ("${{ inputs.use_mkdocs }}" == "true" && "${{ inputs.use_sphinx }}" == "false") ]]; then
+          # (Default to) using MkDocs
+          echo "framework=mkdocs" >> $GITHUB_ENV
+        elif [[ "${{ inputs.use_mkdocs }}" == "false" && "${{ inputs.use_sphinx }}" == "true" ]]; then
+          # Use Sphinx
+          echo "framework=sphinx" >> $GITHUB_ENV
+        else
+          echo "Could not determine what documentation framework to use."
+          echo "Note, the inputs 'use_mkdocs' and 'use_sphinx' are mutually exclusive."
+          echo "The found values:"
+          echo "  use_mkdocs=${{ inputs.use_mkdocs }}"
+          echo "  use_sphinx=${{ inputs.use_sphinx }}"
+          exit 1
+        fi
+
     - name: Checkout ${{ github.repository }}
       uses: actions/checkout@v3
       with:
@@ -276,6 +340,16 @@ jobs:
       uses: actions/setup-python@v4
       with:
         python-version: "${{ inputs.python_version_docs }}"
+
+    - name: Install system dependencies
+      if: inputs.system_dependencies != ''
+      run: |
+        SYSTEM_PACKAGES=()
+        while IFS= read -r line; do
+          if [ -n "${line}" ]; then SYSTEM_PACKAGES+=("${line}"); fi
+        done <<< "${{ inputs.system_dependencies }}"
+
+        sudo apt update && sudo apt install -y "${SYSTEM_PACKAGES[@]}"
 
     - name: Install Python dependencies
       run: |
@@ -288,10 +362,10 @@ jobs:
         pip install git+https://github.com/SINTEF/ci-cd.git@v2.3.1
 
     - name: Update API Reference
-      if: inputs.update_python_api_ref
+      if: env.framework == 'mkdocs' && inputs.update_python_api_ref
       run: |
         if [ -z "${{ inputs.package_dirs }}" ]; then
-          echo "package_dirs MUST be supplied, since update_docs and update_python_api_ref were set to 'true'."
+          echo "'package_dirs' MUST be supplied, since 'update_docs' and 'update_python_api_ref' were set to 'true' and using the MkDocs framework."
           exit 1
         fi
 
@@ -336,10 +410,10 @@ jobs:
           "${SPECIAL_OPTIONS[@]}"
 
     - name: Update landing page
-      if: inputs.update_docs_landing_page
+      if: env.framework == 'mkdocs' && inputs.update_docs_landing_page
       run: |
-        # Ensure the default replacement for LICENSE linking works
-        # with a custom separator
+        # Ensure the default replacement for LICENSE linking works with a custom
+        # separator
         LANDING_PAGE_REPLACEMENTS="${{ inputs.landing_page_replacements }}"
         if [ "${{ inputs.landing_page_replacement_separator }}" != "," ] && [ "${{ inputs.landing_page_replacements }}" == "(LICENSE),(LICENSE.md)" ]; then
           LANDING_PAGE_REPLACEMENTS="${LANDING_PAGE_REPLACEMENTS/,/${{ inputs.landing_page_replacement_separator }}}"
@@ -355,12 +429,41 @@ jobs:
           --replacement-separator="${{ inputs.landing_page_replacement_separator }}" \
           "${REPLACEMENTS[@]}"
 
-    - name: Build MkDocs documentation
+    - name: Build documentation
       run: |
+        # Set STRICT option
+
         if [ "${{ inputs.warnings_as_errors }}" == "true" ]; then
-          STRICT="--strict"
+          if [ "${{ env.framework }}" == "mkdocs" ]; then
+            STRICT="--strict"
+          elif [ "${{ env.framework }}" == "sphinx" ]; then
+            STRICT="-W"
+          else
+            echo "Unknown framework: ${{ env.framework }}"
+            exit 1
+          fi
+
         else
           STRICT=
-          echo "::warning file=ci_tests.yml,line=366,col=9,endColumn=31::Beware that the documentation may succeed building, but will not be rendered or built as intended. To ensure this is the case, set 'warnings_as_errors' to 'true' (using '--strict')."
+          echo "::warning file=ci_tests.yml,line=446,col=11,endColumn=18::Beware that the documentation may succeed building, but will not be rendered or built as intended. To ensure this is the case, set 'warnings_as_errors' to 'true' (using '--strict' (MkDocs) or '-W' (Sphinx))."
         fi
-        mkdocs build ${STRICT}
+
+        # Run build command
+
+        if [ "${{ env.framework }}" == "mkdocs" ]; then
+          mkdocs build ${STRICT}
+
+        elif [ "${{ env.framework }}" == "sphinx" ]; then
+          SPHINX_OPTIONS=()
+          while IFS= read -r line; do
+            if [ -n "${line}" ]; then SPHINX_OPTIONS+=("${line}"); fi
+          done <<< "${{ inputs.sphinx-build_options }}"
+
+          sphinx-build ${STRICT} \
+            "${SPHINX_OPTIONS[@]}" \
+            ${{ inputs.docs_folder }} ${{ inputs.build_target_folder }}
+
+        else
+          echo "Unknown framework: ${{ env.framework }}"
+          exit 1
+        fi
